USE efh_community_0;

ALTER TABLE `post_0` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '帖子ID';
ALTER TABLE `post_1` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '帖子ID';
ALTER TABLE `post_2` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '帖子ID';
ALTER TABLE `post_3` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '帖子ID';

ALTER TABLE `comment_0` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '评论ID';
ALTER TABLE `comment_1` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '评论ID';
ALTER TABLE `comment_2` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '评论ID';
ALTER TABLE `comment_3` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '评论ID';

USE efh_community_1;
ALTER TABLE `post_0` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '帖子ID';
ALTER TABLE `post_1` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '帖子ID';
ALTER TABLE `post_2` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '帖子ID';
ALTER TABLE `post_3` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '帖子ID';
