USE efh_parts;

ALTER TABLE `parts` ADD COLUMN `seller_id` BIGINT NOT NULL DEFAULT 1 COMMENT '卖家ID' AFTER `id`;
ALTER TABLE `parts` ADD COLUMN `sales_count` INT NOT NULL DEFAULT 0 COMMENT '销量' AFTER `status`;
ALTER TABLE `parts` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '配件ID';
